### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ryan-nauman** [ryan-nauman/spotify-mini#1]
- [x] Decide where app will live (~~taskbar~~, tray, ~~mix~~)
- [x] Right click menu? (settings, copy track uri, etc)
- [x] Taskbar/tray icons **_credit forward button by ProSymbols from the Noun Project_**
- [x] Travis ci and appveyor tests
- [ ] Test tray icon/etc on linux
- [ ] Handle resume from sleep
- [ ] Travis ci and appveyor builds pushing to github releases
- [ ] Implement auto-updating, see [electron-builder](https://github.com/electron-userland/electron-builder#auto-update) and ~~[nuts](https://github.com/GitbookIO/nuts)~~ [gh-releases](https://github.com/jenslind/electron-gh-releases) 
- [ ] Handle bowtie:// links so they can be clicked from [bowcase](http://catalog.13bold.com/) e.x. bowtie://install/http://catalog.13bold.com/download.php?id=x
- [ ] Finish stubs in [player.ts](https://github.com/ryan-nauman/spotify-mini/blob/master/src/lib/player.ts) and [Bowtie.ts](https://github.com/ryan-nauman/spotify-mini/blob/master/src/lib/Bowtie.ts)
- [ ] Complete handling of [theme settings](http://library.13bold.com/developing-themes-for-bowtie/key-reference/) in [player.ts](https://github.com/ryan-nauman/spotify-mini/blob/master/src/lib/player.ts)
- [ ] Store downloaded themes in userData folder
- [ ] Persist which theme was last used on restart
- [ ] Add retry logic to [spotify.ts](https://github.com/ryan-nauman/spotify-mini/blob/master/src/lib/spotify.ts) when init fails
- [ ] Create our own theme gallery
- [ ] Create an original default theme
- [ ] Provide non-quartz insanity methods for getting/setting position aka currentFrame() setFrame()
- [ ] Come up with a name... https://developer.spotify.com/design/

> - It shouldn’t imply endorsement by Spotify, but suggesting to users that it is “for Spotify” is acceptable.
> - It cannot begin with “Spot” or be similar to “Spotify” in sound or spelling.
